# Generated by Django 5.1.15 on 2026-09-22 14:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0003_organisationinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        help_text="Organisation-assigned staff/payroll number.", max_length=32
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="full name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="work email")),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("department", models.CharField(blank=True, max_length=150)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On leave"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField(help_text="First day of employment.")),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=20)),
                ("bank_account_name", models.CharField(blank=True, max_length=200)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="tax identification number"
                    ),
                ),
                ("pension_pin", models.CharField(blank=True, max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked login account, if the employee uses the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
                "ordering": ("full_name",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "status"], name="employees_e_organis_c13611_idx"
                    ),
                    models.Index(
                        fields=["organisation", "department"], name="employees_e_organis_504f4c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "employee_number"),
                        name="unique_employee_number_per_org",
                    )
                ],
            },
        ),
    ]
