# Generated by Django 5.1.15 on 2026-05-07 10:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier, e.g. 'oyo-college-of-nursing'.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        help_text="Registered company name as it appears on legal documents.",
                        max_length=200,
                        verbose_name="legal name",
                    ),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True,
                        help_text="Public-facing name, if different from legal name.",
                        max_length=200,
                        verbose_name="trading name",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 (e.g. 'NG', 'GB'). Determines which payroll calculator is used.",
                        max_length=2,
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        help_text="ISO 4217 (e.g. 'NGN', 'GBP', 'USD').", max_length=3
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone name (e.g. 'Africa/Lagos').",
                        max_length=64,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Primary tax registration number for this organisation.",
                        max_length=50,
                        verbose_name="tax identification number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-deletion flag. Inactive organisations cannot be accessed but their data is preserved for audit.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who created this organisation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
                "ordering": ("legal_name",),
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("hr_manager", "HR Manager"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        help_text="The user's role within this organisation.",
                        max_length=32,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive memberships block access but preserve audit history.",
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invited user accepted the invitation.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who issued the invitation. Null if self-created.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships_invited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(
                fields=["country_code", "is_active"], name="organisatio_country_97872e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["organisation", "role", "is_active"], name="organisatio_organis_9212b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["user", "is_active"], name="organisatio_user_id_34c05f_idx"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "organisation"), name="unique_user_organisation_membership"
            ),
        ),
    ]
