# Generated by Django 5.1.15 on 2026-05-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this organisation. NULL for system-seeded orgs (imports, fixtures, automated flows).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organisations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
