# Generated by Django 5.1.15 on 2026-09-22 13:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_alter_organisation_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address the invitation was sent to.", max_length=254
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("hr_manager", "HR Manager"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        max_length=32,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation invitation",
                "verbose_name_plural": "organisation invitations",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "accepted_at", "revoked_at"],
                        name="organisatio_organis_0cc04e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("accepted_at__isnull", True), ("revoked_at__isnull", True)
                        ),
                        fields=("organisation", "email"),
                        name="unique_pending_invitation_per_email_org",
                    )
                ],
            },
        ),
    ]
